name: plco-analysis-ldsc
dependencies:
  - ldsc-rebuild
  - bolt-lmm-genetic-map-hg38
  - liftover-v369
  - ucsc-hg19tohg38
  - plink
  - qsub_job_monitor
  - boost-cpp=1.70
  - r-data.table
  - r-r.utils
  - git
  - git-lfs

