analysis_prefix: first_ca125_level
chips:
  - Omni25
  - OmniX
  - Oncoarray
  - GSA_batch1
  - GSA_batch2
  - GSA_batch3
  - GSA_batch4
  - GSA_batch5
phenotype: first_ca125_level
covariates:
  - bq_age_co
  - center
  - batch.GSA
  - batch.Oncoarray
  - batch.OmniX
  - batch.Omni25
  - is.other.asian
  - PC1
  - PC2
  - PC3
  - PC4
  - PC5
  - PC6
  - PC7
  - PC8
  - PC9
  - PC10
ancestries:
  - European
  - East_Asian
  - Other_Asian_or_Pacific_Islander
  - South_Asian
algorithm:
  - boltlmm
  - plink
  - fastgwa
