analysis_prefix: j_breast_grade2
chips:
  - Omni25
  - OmniX
  - GSA_batch1
  - GSA_batch2
  - GSA_batch3
  - GSA_batch4
  - GSA_batch5
  - Oncoarray
phenotype: j_breast_grade2
covariates:
  - bq_age_co
  - sex
  - is.other.asian
  - PC1
  - PC2
  - PC3
  - PC4
  - PC5
  - PC6
  - PC7
  - PC8
  - PC9
  - PC10
  - center
  - batch.GSA
  - batch.Oncoarray
  - batch.OmniX
  - batch.Omni25
ancestries:
  - European
  - East_Asian
algorithm:
  - saige
  - plink
id_mode: rsid
control_inclusion:
  clean_control: 1
