analysis_prefix: j_panc_cancer_female
## removing OmniX for mysterious convergence reasons, most variants have p == 0 but report convergence :(
chips:
  - Omni25
  - GSA_batch1
  - GSA_batch2
  - GSA_batch3
  - GSA_batch4
  - GSA_batch5
  - Oncoarray
phenotype: j_panc_cancer
covariates:
  - bq_age_co
  - sex
  - is.other.asian
  - PC1
  - PC2
  - PC3
  - PC4
  - PC5
  - PC6
  - PC7
  - PC8
  - PC9
  - PC10
  - center
  - batch.GSA
  - batch.Oncoarray
  - batch.OmniX
  - batch.Omni25
ancestries:
  - European
  - East_Asian
algorithm:
  - saige
  - plink
sex-specific: female
id_mode: rsid
control_type: no-cancer
