analysis_prefix: psares4
chips:
  - Omni25
  - OmniX
  - Oncoarray
  - GSA_batch1
  - GSA_batch2
  - GSA_batch3
  - GSA_batch4
  - GSA_batch5
phenotype: psares4
ancestries:
  - European
  - East_Asian
  - South_Asian
algorithm:
  - boltlmm
frequency_mode: subject
id_mode: rsid
